{{ $name := include "nats.fullname" . }}

cluster:
  name: {{ $name }}
  routes:
  {{- range $i, $e := until (.Values.nats.replicas | int) }}
  - {{ printf "nats://%s-%d.%s-headless:6222" $name $i $name }}
  {{- end }}

{{- if .Values.nats.jetstreamPersistence.enabled }}
jetstream:
  store_dir: {{ .Values.nats.jetstreamPersistence.dir }}
{{- end }}

{{- if .Values.nats.resolverPersistence.enabled }}
resolver:
  dir: {{ .Values.nats.resolverPersistence.dir }}
{{- end }}
