{{- $ := . }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nats.fullname" $ }}-config
  labels:
    {{- include "nats.labels" . | nindent 4 }}
data:
  nats.conf: |
    {{- with $.Values.config }}
    {{- include "nats.formatConfig" (include "nats.loadMergePatch" (dict "file" "nats-config.yaml" "ctx" $ "merge" .merge "patch" .patch) | fromYaml) | nindent 4 }}
    {{- end }}
