apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nats.fullname" . }}-config
  labels:
    {{- include "nats.labels" . | nindent 4 }}
data:
  nats.conf: |
    {{- include "toPrettyRawJson" .config | nindent 4 }}
