{{- $ := . }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.headlessService.name | default (printf "%s-headless" (include "nats.fullname" $)) }}
  labels:
    {{- include "nats.labels" . | nindent 4 }}
    app.kubernetes.io/component: nats-headless
spec:
  selector:
    {{- include "nats.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: nats
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
  {{- range $protocol := list "nats" "leafnodes" "websocket" "mqtt" "cluster" "gateway" "monitor" "profiling" }}
  {{- $configProtocol := get $.Values.config $protocol }}
  {{- if or (eq $protocol "nats") $configProtocol.enabled }}
  - {{ dict "name" $protocol "port" $configProtocol.port "targetPort" $protocol | toYaml | nindent 4 }}
  {{- end }}
  {{- end }}
