{{- $ := . }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nats.fullname" $ }}-headless
  labels:
    {{- include "nats.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "nats.selectorLabels" . | nindent 4 }}
    type: headless
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
  {{- range $protocol := list "nats" "leafnodes" "websocket" "mqtt" "cluster" "gateway" "monitor" "profiling" }}
  {{- $configProtocol := get $.Values.config.protocol $protocol }}
  {{- if eq $configProtocol.enabled true }}
  - {{ dict "name" $protocol "port" $configProtocol.port "targetPort" $protocol | toYaml | nindent 4 }}
  {{- end }}
  {{- end }}
