{{- $ := . }}
{{- with .Values.ingress }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .name | default (printf "%s-ws" (include "nats.fullname" $)) }}
  labels:
    {{- include "nats.labels" $ | nindent 4 }}
    app.kubernetes.io/component: nats
spec:
  {{- with .className }}
  ingressClassName: {{ . | quote }}
  {{- end }}
  rules:
  {{- $path := .path }}
  {{- $pathType := .pathType }}
  {{- range .hosts }}
  - host: {{ . | quote }}
    http:
      paths:
      - path: {{ $path | quote }}
        pathType: {{ $pathType | quote }}
        backend:
          service:
            name: {{ $.Values.service.name | default (include "nats.fullname" $) }}
            port:
              name: websocket
  {{- end }}
  {{- if .tlsSecretName }}
  tls:
    secretName: {{ .tlsSecretName | quote }}
    hosts:
    {{- toYaml .hosts | nindent 4 }}
  {{- end }}
{{- end }}
