{{- $ := . }}
{{- with .Values.jetstream.fileStorage }}
metadata:
  name: {{ include "nats.fullname" $ }}-js-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .size | quote }}
  {{- with .pvc.storageClassName }}
  storageClassName: {{ . | quote }}
  {{- end }}
{{- end }}
