{{- $ := . }}
{{ $name := include "nats.fullname" $ }}
{{- with .Values.config }}

server_name: << $HOSTNAME >>
lame_duck_grace_period: 10s
lame_duck_duration: 30s

########################################
# NATS
########################################
{{- with .protocol.nats }}
{{- if .enabled }}
port: {{ .port }}

{{- with .tls }}
{{- if .enabled }}
tls: {{ include "nats.loadMergePatch" (dict "file" "nats-tls.yaml" "ctx" (merge (dict "tls" .) $) "merge" .merge "patch" .patch) | nindent 2 }}
{{- end }}
{{- end }}

{{- end }}
{{- end }}

########################################
# leafnodes
########################################
{{- with .protocol.leafnodes }}
{{- if .enabled }}
leafnodes:
  port: {{ .port }}

  {{- with .tls }}
  {{- if .enabled }}
  tls: {{ include "nats.loadMergePatch" (dict "file" "nats-tls.yaml" "ctx" (merge (dict "tls" .) $) "merge" .merge "patch" .patch) | nindent 4 }}
  {{- end }}
  {{- end }}

{{- end }}
{{- end }}

########################################
# websocket
########################################
{{- with .protocol.websocket }}
{{- if .enabled }}
websocket:
  port: {{ .port }}
  {{- with .tls }}
  {{- if .enabled }}
  tls: {{ include "nats.loadMergePatch" (dict "file" "nats-tls.yaml" "ctx" (merge (dict "tls" .) $) "merge" .merge "patch" .patch) | nindent 4 }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}

########################################
# MQTT
########################################
{{- with .protocol.mqtt }}
{{- if .enabled }}
mqtt:
  port: {{ .port }}

  {{- with .tls }}
  {{- if .enabled }}
  tls: {{ include "nats.loadMergePatch" (dict "file" "nats-tls.yaml" "ctx" (merge (dict "tls" .) $) "merge" .merge "patch" .patch) | nindent 4 }}
  {{- end }}
  {{- end }}

{{- end }}
{{- end }}

########################################
# cluster
########################################
{{- with .protocol.cluster }}
{{- if .enabled }}
cluster:
  name: {{ $name }}
  port: {{ .port }}
  no_advertise: true
  routes:
  {{- range $i, $_ := until ($.Values.statefulSet.replicas | int) }}
  - {{ printf "nats://%s-%d.%s-headless:6222" $name $i $name }}
  {{- end }}

  {{- with .tls }}
  {{- if .enabled }}
  tls: {{ include "nats.loadMergePatch" (dict "file" "nats-tls.yaml" "ctx" (merge (dict "tls" .) $) "merge" .merge "patch" .patch) | nindent 4 }}
  {{- end }}
  {{- end }}

{{- end }}
{{- end }}

########################################
# gateway
########################################
{{- with .protocol.gateway }}
{{- if .enabled }}
gateway:
  port: {{ .port }}

  {{- with .tls }}
  {{- if .enabled }}
  tls: {{ include "nats.loadMergePatch" (dict "file" "nats-tls.yaml" "ctx" (merge (dict "tls" .) $) "merge" .merge "patch" .patch) | nindent 4 }}
  {{- end }}
  {{- end }}

{{- end }}
{{- end }}

########################################
# monitor
########################################
{{- with .protocol.monitor }}
{{- if .enabled }}
{{- if $.Values.config.protocol.nats.tls.enabled }}
https_port: {{ .port }}
{{- else }}
http_port: {{ .port }}
{{- end }}
{{- end }}
{{- end }}

########################################
# profiling
########################################
{{- with .protocol.profiling }}
{{- if .enabled }}
prof_port: {{ .port }}
{{- end }}
{{- end }}

########################################
# jetstream
########################################
{{- with $.Values.config.jetstream -}}
{{- if .enabled }}
jetstream:
  {{- with .memStorage }}
  {{- if .enabled }}
  max_memory_store: << {{ .size }} >>
  {{- else }}
  max_memory_store: 0
  {{- end }}
  {{- end }}
  {{- with .fileStorage }}
  {{- if .enabled }}
  max_file_store: << {{ .size }} >>
  store_dir: {{ .dir }}
  {{- else }}
  max_file_store: 0
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}

########################################
# resolver
########################################
{{- with $.Values.resolverPvc -}}
{{- if .enabled }}
resolver:
  dir: {{ .dir }}
{{- end }}
{{- end }}

{{- end }}
