{{- $ := . }}
{{ $name := include "nats.fullname" . }}
cluster:
  name: {{ $name }}
  routes:
  {{- range $i, $e := until (.Values.statefulSet.replicas | int) }}
  - {{ printf "nats://%s-%d.%s-headless:6222" $name $i $name }}
  {{- end }}

{{- if .Values.jetstreamPvc.enabled }}
jetstream:
  store_dir: {{ .Values.nats.jetstreamPvc.dir }}
{{- end }}

{{- if .Values.resolverPvc.enabled }}
resolver:
  dir: {{ .Values.resolverPvc.dir }}
{{- end }}
