{{- $ := . }}
metadata:
  labels:
    {{- include "nats.labels" . | nindent 8 }}
spec:
  volumes:
  - name: config
    configMap:
      name: {{ include "nats.fullname" $ }}-config
  terminationGracePeriodSeconds: 60
  containers:
  {{- with $.Values.nats }}
  - {{ include "nats.loadMergePatch" (dict "file" "nats-container.yaml" "ctx" $ "merge" .merge "patch" .patch) | nindent 4 }}
  {{- end }}
