apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "nats.fullname" $ }}
  labels:
    {{- include "nats.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "nats.selectorLabels" . | nindent 6 }}
  podMetricsEndpoints:
  - port: prom-metrics
