{{- $ := . }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nats.fullname" $ }}
  labels:
    {{- include "nats.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "nats.selectorLabels" . | nindent 4 }}
  ports:
  {{- range $protocol := list "nats" "leafnodes" "websocket" "mqtt" "cluster" "gateway" "monitor" "profiling" }}
  {{- $configProtocol := get $.Values.config.protocol $protocol }}
  {{- $servicePort := get $.Values.service.ports $protocol }}
  {{- if and (eq $configProtocol.enabled true) (eq $servicePort.enabled true) }}
  - {{ merge (dict "name" $protocol "port" $configProtocol.port "targetPort" $protocol) (omit $servicePort "enabled") | toYaml | nindent 4 }}
  {{- end }}
  {{- end }}
