apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "nats.fullname" $ }}
spec:
  selector:
    matchLabels:
      {{- include "nats.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.nats.replicas }}
  serviceName: {{ include "nats.fullname" $ }}-headless
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        {{- include "nats.labels" . | nindent 8 }}
    spec:
      volumes:
      - name: config
        configMap:
          name: {{ include "nats.fullname" $ }}-config
      terminationGracePeriodSeconds: 60
      containers:
      - name: nats
        image: {{ include "nats.image" .Values.nats.image }}
        imagePullPolicy: {{ .Values.nats.image.pullPolicy }}
        ports:
        {{- with .config.port }}
        - containerPort: {{ . }}
          name: nats
        {{- end }}
        {{ with .config.cluster }}
        {{ with .port }}
        - containerPort: {{ . }}
          name: cluster
        {{- end }}
        {{- end }}
        {{ with .config.leafnode }}
        {{ with .port }}
        - containerPort: {{ . }}
          name: leafnode
        {{- end }}
        {{- end }}
        {{ with .config.gateway }}
        {{ with .port }}
        - containerPort: {{ . }}
          name: gateway
        {{- end }}
        {{- end }}
        {{ with .config.http }}
        - containerPort: {{ . }}
          name: monitor
        {{- end }}
        {{ with .config.mqtt }}
        {{ with .port }}
        - containerPort: {{ . }}
          name: mqtt
        {{- end }}
        {{- end }}
        {{ with .config.websocket }}
        {{ with .port }}
        - containerPort: {{ . }}
          name: websocket
        {{- end }}
        {{- end }}
        {{ with .config.profiling }}
        {{ with .port }}
        - containerPort: {{ . }}
          name: profiling
        {{- end }}
        {{- end }}
        command:
        - "nats-server"
        - "--config"
        - "/etc/nats-config/nats.conf"
        volumeMounts:
        - name: config
          mountPath: /etc/nats-config
        {{- with .Values.nats.jetstreamPvc }}
        {{- if .enabled }}
        - name: {{ include "nats.fullname" $ }}-js-pvc
          mountPath: {{ .dir }}
        {{- end }}
        {{- end }}
        {{- with .Values.nats.resolverPersistence }}
        {{- if .enabled }}
        - name: {{ include "nats.fullname" $ }}-jwt-pvc
          mountPath: {{ .dir }}
        {{- end }}
        {{- end }}
  {{- if or .Values.nats.jetstreamPersistence.enabled .Values.nats.resolverPersistence.enabled }}
  volumeClaimTemplates:
  {{- with .Values.nats.jetstreamPvc }}
  {{- if .enabled }}
  - metadata:
      name: {{ include "nats.fullname" $ }}-js-pvc
    spec:
      accessModes:
      - ReadWriteOncePod
      resources:
        requests:
          storage: {{ .size | quote }}
      {{- with .storageClassName }}
      storageClassName: {{ . | quote }}
      {{- end }}
  {{- end }}
  {{- end }}
  {{- with .Values.nats.resolverPersistence }}
  {{- if .enabled }}
  - metadata:
      name: {{ include "nats.fullname" $ }}-jwt-pvc
    spec:
      accessModes:
      - ReadWriteOncePod
      resources:
        requests:
          storage: {{ .size | quote }}
      {{- with .storageClassName }}
      storageClassName: {{ . | quote }}
      {{- end }}
  {{- end }}
  {{- end }}
  {{- end }}