{{- $contextName := .contextName }}
{{- $caSet := false }}

# url
{{- if .Values.service.enabled }}
url: nats://{{ .Values.service.name }}
{{- else }}
url: nats://{{ .Values.headlessService.name }}
{{- end }}

{{- with .context }}

# creds
{{- with .creds}}
{{- if .contents }}
creds: /etc/nats-contents/{{ $contextName }}.creds
{{- else if .secretName }}
creds: /etc/nats-creds/{{ $contextName }}/{{ .key }}
{{- end }}
{{- end }}

# nkey
{{- with .nkey}}
{{- if .contents }}
nkey: /etc/nats-contents/{{ $contextName }}.nk
{{- else if .secretName }}
nkey: /etc/nats-nkeys/{{ $contextName }}/{{ .key }}
{{- end }}
{{- end }}

# tls
{{- with .tls }}
{{- if .secretName }}
{{- if and .cert .key }}
cert: /etc/nats-certs/{{ $contextName }}/{{ .cert }}
key: /etc/nats-certs/{{ $contextName }}/{{ .key }}
{{- end }}
{{- if .ca }}
{{- $caSet = true }}
ca: /etc/nats-certs/{{ $contextName }}/{{ .ca }}
{{- end }}
{{- end }}
{{- end }}

{{- end }}