{{- with .Values.config.cluster }}
name: {{ $.Values.statefulSet.name }}
port: {{ .port }}
no_advertise: true
routes:
{{- range $i, $_ := until ($.Values.replicas | int) }}
- {{ printf "nats://%s-%d.%s:6222" $.Values.statefulSet.name $i $.Values.headlessService.name }}
{{- end }}

{{- with .tls }}
{{- if .enabled }}
tls: {{ include "nats.loadMergePatch" (merge (dict "file" "config/tls.yaml" "ctx" (merge (dict "tls" .) $)) .) | nindent 4 }}
{{- end }}
{{- end }}
{{- end }}
