metadata:
  labels:
    {{- include "natsBox.labels" $ | nindent 4 }}
spec:
  containers:
  {{- with .Values.natsBox.container }}
  - {{ include "nats.loadMergePatch" (merge (dict "file" "nats-box/deployment/container.yaml" "ctx" $) .) | nindent 4 }}
  {{- end }}

  volumes:
  # context secret
  - name: context
    secret:
      secretName: {{ .Values.natsBox.contextSecret.name }}
  # contents secret
  - name: contents
    secret:
      secretName: {{ .Values.natsBox.contentsSecret.name }}
  # context secrets
  {{- range $ctxKey, $ctxVal := .Values.natsBox.context }}
  {{- range $secretKey, $secretVal := dict "creds" "nats-creds" "nkey" "nats-nkeys" "tls" "nats-certs" }}
  {{- $secret := get $ctxVal $secretKey }}
  {{- if $secret.secretName }}
  - name: ctx-{{ $ctxKey }}-{{ $secretKey }}
    secret:
      secretName: {{ $secret.secretName | quote }}
  {{- end }}
  {{- end }}
  {{- end }}
