{{- $ := . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nats.fullname" $ }}-box-contents
  labels:
    {{- include "nats.labels" . | nindent 4 }}
    app.kubernetes.io/component: nats-box-contents
type: Opaque
stringData:
  {{- range $ctxKey, $ctxVal := .Values.natsBox.context }}
  {{- range $secretKey, $secretVal := dict "creds" "creds" "nkey" "nk" }}
  {{- $secret := get $ctxVal $secretKey }}
  {{- if $secret.contents }}
  "{{ $ctxKey }}.{{ $secretVal }}": {{ $secret.contents | quote }}
  {{- end }}
  {{- end }}
  {{- end }}
