name: nats-box
{{ include "nats.image" (merge (pick $.Values "global") .Values.natsBox.container.image) }}

{{- with .Values.natsBox.container.env }}
env:
{{- include "nats.env" . }}
{{- end }}

command:
- sh
- -ec
- |
  work_dir="$(pwd)"
  mkdir -p "$XDG_CONFIG_HOME/nats"
  cd "$XDG_CONFIG_HOME/nats"
  if ! [ -s context ]; then
    ln -s /etc/nats-contexts context
  fi
  if ! [ -f context.txt ]; then
    echo -n "default" > context.txt
  fi
  cd "$work_dir"
  exec sh -ec "$0"
args:
- |
  stop_signal () {
    exit 0
  }
  trap stop_signal SIGINT SIGTERM
  while true; do
    sleep 0.1
  done
volumeMounts:
- name: contexts
  mountPath: /etc/nats-contexts
- name: contents
  mountPath: /etc/nats-contents
{{- range $ctxKey, $ctxVal := .Values.natsBox.contexts }}
{{- range $secretKey, $secretVal := dict "creds" "nats-creds" "nkey" "nats-nkeys" "tls" "nats-certs" }}
{{- $secret := get $ctxVal $secretKey }}
{{- if and $secret $secret.secretName }}
- name: ctx-{{ $ctxKey }}-{{ $secretKey }}
  mountPath: /etc/{{ $secretVal }}/{{ $ctxKey }}
{{- end }}
{{- end }}
{{- end }}
