nats:
  image:
    repository: nats
    tag: 2.9.15-alpine
    pullPolicy: IfNotPresent
    # registry: docker.io

  replicas: 1

  jetstreamPvc:
    enabled: false
    # mount the pvc and set NATS config `jetstream.store_dir`
    dir: /data/jetstream
    size: 10Gi
    storageClassName:

    # nats stateful set -> volume claim templates -> jetstream pvc
    pvcTemplate: {}
    pvcTemplatePatch: []

  jwtPvc:
    enabled: false
    # mount the pvc and set NATS config `resolver.dir`
    dir: /data/jwt
    size: 1Gi
    storageClassName:

    # nats stateful set -> volume claim templates -> jwt pvc
    pvcTemplate: {}
    pvcTemplatePatch: []

  # nats.conf
  config:
    port: 4222
    cluster:
      port: 6222
    http: 8222
  configPatch: []

  # nats stateful set
  statefulSet: {}
  statefulSetPatch: []

  # nats stateful set -> pod template
  podTemplate: {}
  podTemplatePatch: []

  # nats stateful set -> pod template -> nats container
  container: {}
  containerPatch: []

  # nats service
  service: {}
  servicePatch: []

  # nats headless service
  headlessService: {}
  headlessServicePatch: []

  # nats config map
  configMap: {}
  configMapPatch: []
