############################################################
# NATS config
############################################################
config:
  protocol:
    nats:
      enabled: true
      port: 4222
    leafnodes:
      enabled: false
      port: 7422
    websocket:
      enabled: false
      port: 8080
    mqtt:
      enabled: false
      port: 1883
    cluster:
      enabled: true
      port: 6222
    gateway:
      enabled: false
      port: 7222
    monitor:
      enabled: true
      port: 8222
    profiling:
      enabled: false
      port: 65432

  # merge or patch the nats config
  # https://docs.nats.io/running-a-nats-service/configuration
  # following special rules apply
  #  1. strings that start with << and end with >> will be unquoted
  #     use this for variables and numbers with units
  #  2. keys ending in $include will be switched to include directives
  #     keys are sorted alphabetically, use prefix before $includes to control includes ordering
  #     paths should be relative to /etc/nats-config/nats.conf
  # example:
  #
  #   merge:
  #     $include: ./my-config.conf
  #     zzz$include: ./my-config-last.conf
  #     server_name: nats
  #     authorization:
  #       token: << $TOKEN >>
  #     jetstream:
  #       max_mem: << 1GB >>
  #
  # will yield the config:
  # {
  #   include ./my-config.conf;
  #   "authorization": {
  #     "token": $TOKEN
  #   },
  #   "jetstream": {
  #     "max_mem": 1GB
  #   },
  #   "server_name": "nats",
  #   include ./my-config-last.conf;
  # }
  merge: {}
  patch: []


############################################################
# stateful set
############################################################
statefulSet:
  replicas: 1

  # merge or patch the stateful set
  # https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.24/#statefulset-v1-apps
  merge: {}
  patch: []


############################################################
# stateful set -> pod template
############################################################
podTemplate:
  # merge or patch the pod template
  # https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.24/#pod-v1-core
  merge: {}
  patch: []


############################################################
# stateful set -> pod template -> nats container
############################################################
nats:
  image:
    repository: nats
    tag: 2.9.15-alpine
    pullPolicy: IfNotPresent
    # registry: docker.io

  # container port options
  # port must be enabled in the config.protocol section also
  # https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.24/#containerport-v1-core
  ports:
    nats: {}
    leafnodes: {}
    websocket: {}
    mqtt: {}
    cluster: {}
    gateway: {}
    monitor: {}
    profiling: {}

  # merge or patch the container
  # https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.24/#container-v1-core
  merge: {}
  patch: []


################################################################################
# stateful set -> volume claim templates -> jetstream pvc
############################################################
jetstreamPvc:
  enabled: false
  # mount the pvc and set NATS config `jetstream.store_dir`
  dir: /data/jetstream
  size: 10Gi
  storageClassName:
  
  # merge or patch the pvc
  # https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.24/#persistentvolumeclaim-v1-core  
  merge: {}
  patch: []


############################################################
# stateful set -> volume claim templates -> resolver pvc
############################################################
resolverPvc:
  enabled: false
  # mount the pvc and set NATS config `resolver.dir`
  dir: /data/resolver
  size: 1Gi
  storageClassName:

  # merge or patch the pvc
  # https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.24/#persistentvolumeclaim-v1-core  
  merge: {}
  patch: []


############################################################
# config map
############################################################
configMap:
  # merge or patch the config map
  # https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.24/#configmap-v1-core
  merge: {}
  patch: []


############################################################
# service
############################################################
service:
  enabled: true

  # service port options
  # additional boolean field enable to control whether port is exposed in the service
  # port must be enabled in the config.protocol section also
  # https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.24/#serviceport-v1-core
  ports:
    nats:
      enabled: true
    leafnodes:
      enabled: true
    websocket:
      enabled: true
    mqtt:
      enabled: true
    cluster:
      enabled: false
    gateway:
      enabled: false
    monitor:
      enabled: false
    profiling:
      enabled: false

  # merge or patch the service
  # https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.24/#service-v1-core
  merge: {}
  patch: []


############################################################
# headless service
############################################################
headlessService:
  # merge or patch the headless service
  # https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.24/#service-v1-core
  merge: {}
  patch: []
