{{- $values := get (include "tplYaml" (dict "doc" .Values "ctx" $) | fromJson) "doc" }}
{{- $_ := set $ "Values" $values -}}
---
# config-map.yaml
{{- with .Values.nats.config }}
{{- $config := include "nats.loadMergePatch" (merge (dict "file" "nats/config/config.yaml" "ctx" $) .) | fromYaml }}
{{- $_ := set $ "config" $config -}}
{{- end }}
{{- with .Values.nats.configMap }}
{{- $configMap := include "nats.loadMergePatch" (merge (dict "file" "nats/config-map.yaml" "ctx" $) .) }}
{{ $configMap }}
{{- $_ := set $ "configChecksum" (sha256sum $configMap) -}}
{{- end }}

---
# stateful-set.yaml
{{- with .Values.nats.statefulSet }}
{{ include "nats.loadMergePatch" (merge (dict "file" "nats/stateful-set/stateful-set.yaml" "ctx" $) .) }}
{{- end }}

---
# headless-service.yaml
{{- with .Values.nats.headlessService }}
{{ include "nats.loadMergePatch" (merge (dict "file" "nats/headless-service.yaml" "ctx" $) .) }}
{{- end }}

{{- with .Values.nats.service }}
{{- if .enabled }}
---
# service.yaml
{{ include "nats.loadMergePatch" (merge (dict "file" "nats/service.yaml" "ctx" $) .) }}
{{- end }}
{{- end }}

{{- with .Values.promExporter }}
{{- if and .enabled .podMonitor.enabled }}
{{- with .podMonitor }}
---
# prom-exporter-pod-monitor.yaml
{{ include "nats.loadMergePatch" (merge (dict "file" "nats/prom-exporter-pod-monitor.yaml" "ctx" $) .) }}
{{- end }}
{{- end }}
{{- end }}

{{- with .Values.natsBox }}
{{- if .enabled }}
{{- with .deployment}}
---
# nats-box/deployment.yaml
{{ include "nats.loadMergePatch" (merge (dict "file" "nats-box/deployment/deployment.yaml" "ctx" $) .) }}
{{- end }}
{{- with .contextSecret}}
---
# nats-box/context-secret.yaml
{{ include "nats.loadMergePatch" (merge (dict "file" "nats-box/context-secret/context-secret.yaml" "ctx" $) .) }}
{{- end }}
{{- with .deployment}}
---
# nats-box/contents-secret.yaml
{{ include "nats.loadMergePatch" (merge (dict "file" "nats-box/contents-secret.yaml" "ctx" $) .) }}
{{- end }}
{{- end }}
{{- end }}
