{{- $values := get (include "tplYaml" (dict "doc" .Values "ctx" $) | fromJson) "doc" }}
{{- $_ := set $ "Values" $values -}}
---
# config-map.yaml
{{- with .Values.config }}
{{- $config := include "nats.loadMergePatch" (merge (dict "file" "nats-config/nats-config.yaml" "ctx" $) .) | fromYaml }}
{{- $_ := set $ "config" $config -}}
{{- end }}
{{- with .Values.configMap }}
{{- $configMap := include "nats.loadMergePatch" (merge (dict "file" "config-map.yaml" "ctx" $) .) }}
{{ $configMap }}
{{- $_ := set $ "configChecksum" (sha256sum $configMap) -}}
{{- end }}

---
# stateful-set.yaml
{{- with .Values.statefulSet }}
{{ include "nats.loadMergePatch" (merge (dict "file" "stateful-set/stateful-set.yaml" "ctx" $) .) }}
{{- end }}

---
# headless-service.yaml
{{- with .Values.headlessService }}
{{ include "nats.loadMergePatch" (merge (dict "file" "headless-service.yaml" "ctx" $) .) }}
{{- end }}

{{- with .Values.service }}
{{- if .enabled }}
---
# service.yaml
{{ include "nats.loadMergePatch" (merge (dict "file" "service.yaml" "ctx" $) .) }}
{{- end }}
{{- end }}

{{- with .Values.promExporter }}
{{- if and .enabled .podMonitor.enabled }}
{{- with .podMonitor }}
---
# prom-exporter-pod-monitor.yaml
{{ include "nats.loadMergePatch" (merge (dict "file" "prom-exporter-pod-monitor.yaml" "ctx" $) .) }}
{{- end }}
{{- end }}
{{- end }}
