
{{- $values := get (include "tplYaml" (dict "doc" .Values "ctx" $) | fromJson) "doc" }}
{{- $_ := set $ "Values" $values -}}
---
# stateful-set.yaml
{{- with .Values.statefulSet }}
{{ include "nats.loadMergePatch" (dict "file" "stateful-set.yaml" "ctx" $ "merge" .merge "patch" .patch) }}
{{- end }}

---
# headless-service.yaml
{{- with .Values.headlessService }}
{{ include "nats.loadMergePatch" (dict "file" "headless-service.yaml" "ctx" $ "merge" .merge "patch" .patch) }}
{{- end }}

{{- with .Values.service }}
{{- if .enabled }}
---
#service
{{ include "nats.loadMergePatch" (dict "file" "service.yaml" "ctx" $ "merge" .merge "patch" .patch) }}
{{- end }}
{{- end }}

---
# config-map.yaml
{{- with .Values.configMap }}
{{ include "nats.loadMergePatch" (dict "file" "config-map.yaml" "ctx" $ "merge" .merge "patch" .patch) }}
{{- end }}
