{{- $ := . }}
{{- with .Values.config.resolver.pvc }}
metadata:
  name: {{ include "nats.fullname" $ }}-resolver-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .size | quote }}
  {{- with .storageClassName }}
  storageClassName: {{ . | quote }}
  {{- end }}
{{- end }}
