{{- $ := . }}
{{- with .Values.config.resolver.pvc }}
metadata:
  name: {{ .name | default (printf "%s-resolver" (include "nats.fullname" $)) }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .size | quote }}
  {{- with .storageClassName }}
  storageClassName: {{ . | quote }}
  {{- end }}
{{- end }}
